function initializeFigure(obj)

    fig   	= 43;
    hfig 	= figure(fig);
    clf(fig)
    set(hfig,...
        'Units',        'normalized',...
        'Position',     [0.5 0 0.5 1])
    
    obj.BackgroundAxisHandle = axes(hfig,...
        'Units',        'normalized',...
        'Position',     [0 0 1 1],...
        'NextPlot',     'add',...
        'XColor',       'none',...
        'YColor',       'none');
    
    
    uAz     = unique(cat(1,obj.RasterData.Az));
    nUAz    = numel(uAz);
    
    spnx  	= 3;
    spny 	= nUAz;
    spi     = reshape(1:spnx*spny,spnx,spny)';
    
    header  = 0.1;
    
    obj.TitleHandle = text(0.05,1 - header + 0.01,'',...
        'HorizontalAlignment',      'left',...
        'VerticalAlignment',        'bottom',...
        'FontSize',                 16);
    
    hsp     = gobjects(spnx*spny,1);
    for row = 1:spny
        for col = 1:spnx
            position    = [(col - 1)/spnx,...
                           ((1 - header)*(spny - row))/spny,...
                           1/spnx,...
                           (1 - header)/spny];
            hsp(spi(row,col)) = axes(hfig,...
                'Units',            'normalized',...
                'Position',         position,...
                'NextPlot',         'add',...
                'DataAspectRatio',  ones(1,3),...
                'XColor',           'none',...
                'YColor',           'none');
        end
    end
    hfig.UserData       = linkprop(reshape(hsp(spi(1:spny,1:2)),[],1),{'XLim','YLim'});
    
    
	obj.AxesMeta        = struct;
    obj.AxesMeta.spnx  	= spnx;
    obj.AxesMeta.spny 	= spny;
    obj.AxesMeta.spi	= spi;
    
    obj.FigureHandles   = hfig;
    obj.AxesHandles     = hsp;
    
    drawBackground(obj)
    initializeDigraph(obj)
    zoomToRaster(obj)
end